const EXTRA = {
  "curator.muslimTitle": "Muslim kids channels",
  "curator.muslimText": "Tap Add to allow a trusted kids channel for this age. It is filed under Islam and stays on this device.",
  "curator.muslimAdded": "{name} is on the feed for this age.",
  "curator.muslimAlready": "{name} is already added.",
  "curator.videoTitle": "Add one video",
  "curator.videoText": "Paste a YouTube video link. It is saved for this age under Islam. Optionally allow the whole channel too.",
  "curator.videoPlaceholder": "youtube.com/watch?v=… or youtu.be/…",
  "curator.videoAlsoChannel": "Also allow this channel",
  "curator.videoAdded": "Saved “{title}” for this age.",
  "curator.videoBad": "Paste a YouTube video link.",
  "ageGroup.teen_13_16": "Teen (13–16)",
  "watch.allCategories": "All",
  "category.faith": "Faith & Values",
  "category.faith.islam": "Islam",
  "category.Coding_Technology": "Coding",
  "category.AI": "AI",
  "category.Film_Making": "Film making",
  "category.Digital_Skills": "Digital skills",
};
